"""empty message

Revision ID: d82f29845758
Revises: 52d59dc81e2c
Create Date: 2025-09-13 23:51:08.103658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82f29845758'
down_revision = '52d59dc81e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creatorid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_unit_creatorid', 'user', ['creatorid'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_unit_creatorid', type_='foreignkey')
        batch_op.drop_column('creatorid')

    # ### end Alembic commands ###
